"""Generic Packed Absorber Simulator V4 — Phase 3 property-resolution layer."""

from .models import (
    CarrierGasSpec,
    ConfidenceClass,
    DataProvenance,
    EquilibriumPair,
    GasTransportPair,
    LiquidTransportPair,
    PackingSpec,
    SoluteSpec,
    SolventSpec,
)
from .reference_data import REFERENCE_ID, ReferenceDataBundle, locked_reference_data
from .registry import (
    AbsorberDataRegistry,
    DuplicateRegistrationError,
    MissingPairDataError,
    PairAvailability,
    RegistryError,
    RegistryReadiness,
    UnknownEntityError,
    build_reference_registry,
)
from .resolver import (
    CarrierPropertyOverrides,
    ComponentPropertyOverrides,
    CorrelationEstimate,
    InvalidPropertyOverrideError,
    MissingPropertyError,
    PropertyResolutionError,
    PropertyResolver,
    ResolutionTier,
    ResolvedCarrierState,
    ResolvedComponentProperties,
    ResolvedEquilibrium,
    ResolvedProperty,
    ResolvedSolventState,
    SolventPropertyOverrides,
    UnsupportedPropertyModelError,
    build_reference_resolver,
)

__all__ = [
    "CarrierGasSpec",
    "ConfidenceClass",
    "DataProvenance",
    "EquilibriumPair",
    "GasTransportPair",
    "LiquidTransportPair",
    "PackingSpec",
    "SoluteSpec",
    "SolventSpec",
    "REFERENCE_ID",
    "ReferenceDataBundle",
    "locked_reference_data",
    "AbsorberDataRegistry",
    "RegistryError",
    "DuplicateRegistrationError",
    "UnknownEntityError",
    "MissingPairDataError",
    "PairAvailability",
    "RegistryReadiness",
    "build_reference_registry",
    "PropertyResolver",
    "PropertyResolutionError",
    "MissingPropertyError",
    "UnsupportedPropertyModelError",
    "InvalidPropertyOverrideError",
    "ResolutionTier",
    "ResolvedProperty",
    "CorrelationEstimate",
    "ComponentPropertyOverrides",
    "CarrierPropertyOverrides",
    "SolventPropertyOverrides",
    "ResolvedCarrierState",
    "ResolvedSolventState",
    "ResolvedEquilibrium",
    "ResolvedComponentProperties",
    "build_reference_resolver",
]
