"""Generic Packed Absorber Simulator V4 — Phase 11 property estimation correlations."""

from .models import (
    CarrierGasSpec,
    ConfidenceClass,
    DataProvenance,
    EquilibriumPair,
    GasTransportPair,
    LiquidTransportPair,
    PackingSpec,
    SoluteSpec,
    SolventSpec,
)
from .reference_data import REFERENCE_ID, ReferenceDataBundle, locked_reference_data

from .correlations import (
    CorrelationCalculation,
    CorrelationInputError,
    fuller_gas_diffusivity_m2_s,
    wilke_chang_liquid_diffusivity_m2_s,
)
from .registry import (
    AbsorberDataRegistry,
    DuplicateRegistrationError,
    MissingPairDataError,
    PairAvailability,
    RegistryError,
    RegistryReadiness,
    UnknownEntityError,
    build_reference_registry,
)
from .resolver import (
    CarrierPropertyOverrides,
    ComponentPropertyOverrides,
    CorrelationEstimate,
    InvalidPropertyOverrideError,
    MissingPropertyError,
    PropertyResolutionError,
    PropertyResolver,
    ResolutionTier,
    ResolvedCarrierState,
    ResolvedComponentProperties,
    ResolvedEquilibrium,
    ResolvedProperty,
    ResolvedSolventState,
    SolventPropertyOverrides,
    UnsupportedPropertyModelError,
    build_reference_resolver,
)

from .mass_transfer import (
    AbsorberOperatingPoint,
    CommonOndaState,
    ComponentMassTransferResult,
    InvalidMassTransferInput,
    MassTransferError,
    calculate_common_onda_state,
    calculate_component_mass_transfer,
    evaluate_component_from_resolver,
)


from .hydraulics import (
    FloodingResult,
    GPDCFloodingSolveError,
    HydraulicResult,
    HydraulicsError,
    InvalidHydraulicInput,
    PackingFactorResult,
    PressureDropResult,
    calculate_flooding,
    calculate_hydraulics,
    calculate_pressure_drop,
    evaluate_hydraulics_from_resolver,
    gpdc_flood_curve_cp,
    resolve_packing_factor,
)

from .countercurrent import (
    BoundaryConditionSolveError,
    ComponentBoundaryConditions,
    ComponentCounterCurrentResult,
    CounterCurrentSolverError,
    CounterCurrentSolverOptions,
    IndependentSolutesResult,
    InvalidBoundaryCondition,
    ODEIntegrationError,
    SolverDiagnostics,
    solve_component_countercurrent,
    solve_independent_solutes,
)


from .applicability import (
    ApplicabilityCase,
    ApplicabilityIssue,
    ApplicabilityReport,
    ConfidenceLevel,
    ConfidenceSummary,
    IssueSeverity,
    ReadinessStatus,
    assess_post_applicability,
    assess_pre_applicability,
)


from .parity import (
    FullParityReport,
    ParityMetricResult,
    ParityTolerance,
    ReferenceMetric,
    REFERENCE_SOURCE_LABEL,
    REFERENCE_SOURCE_SHA256,
    V3_REFERENCE_METRICS,
    reference_chain_health,
    run_full_v3_parity,
)

from .units import (
    CompositionFractionBasis,
    ComponentGasReport,
    ConcentrationTarget,
    DEFAULT_NORMAL_CONDITIONS,
    GasConcentrationBasis,
    GasStreamBalance,
    GasStreamReport,
    MixtureInputResult,
    NormalConditions,
    UnitConversionError,
    actual_m3_h_to_normal_m3_h,
    canonical_y_from_component_concentrations,
    canonical_y_from_total_and_fractions,
    component_concentration_to_y,
    component_y_to_concentration,
    gas_stream_balance,
    liquid_mg_L_to_x_dilute,
    liquid_x_to_mg_L_dilute,
    normal_m3_h_to_actual_m3_h,
    report_gas_stream,
)

__all__ = [
    "FullParityReport",
    "ParityMetricResult",
    "ParityTolerance",
    "ReferenceMetric",
    "REFERENCE_SOURCE_LABEL",
    "REFERENCE_SOURCE_SHA256",
    "V3_REFERENCE_METRICS",
    "reference_chain_health",
    "run_full_v3_parity",
    "ApplicabilityCase",
    "ApplicabilityIssue",
    "ApplicabilityReport",
    "ConfidenceLevel",
    "ConfidenceSummary",
    "IssueSeverity",
    "ReadinessStatus",
    "assess_pre_applicability",
    "assess_post_applicability",
    "CompositionFractionBasis",
    "ComponentGasReport",
    "ConcentrationTarget",
    "DEFAULT_NORMAL_CONDITIONS",
    "GasConcentrationBasis",
    "GasStreamBalance",
    "GasStreamReport",
    "MixtureInputResult",
    "NormalConditions",
    "UnitConversionError",
    "actual_m3_h_to_normal_m3_h",
    "canonical_y_from_component_concentrations",
    "canonical_y_from_total_and_fractions",
    "component_concentration_to_y",
    "component_y_to_concentration",
    "gas_stream_balance",
    "liquid_mg_L_to_x_dilute",
    "liquid_x_to_mg_L_dilute",
    "normal_m3_h_to_actual_m3_h",
    "report_gas_stream",
    "PackingFactorResult",
    "PressureDropResult",
    "FloodingResult",
    "HydraulicResult",
    "HydraulicsError",
    "InvalidHydraulicInput",
    "GPDCFloodingSolveError",
    "resolve_packing_factor",
    "gpdc_flood_curve_cp",
    "calculate_pressure_drop",
    "calculate_flooding",
    "calculate_hydraulics",
    "evaluate_hydraulics_from_resolver",
    "ComponentBoundaryConditions",
    "CounterCurrentSolverOptions",
    "SolverDiagnostics",
    "ComponentCounterCurrentResult",
    "IndependentSolutesResult",
    "CounterCurrentSolverError",
    "InvalidBoundaryCondition",
    "BoundaryConditionSolveError",
    "ODEIntegrationError",
    "solve_component_countercurrent",
    "solve_independent_solutes",
    "AbsorberOperatingPoint",
    "CommonOndaState",
    "ComponentMassTransferResult",
    "MassTransferError",
    "InvalidMassTransferInput",
    "calculate_common_onda_state",
    "calculate_component_mass_transfer",
    "evaluate_component_from_resolver",
    "CarrierGasSpec",
    "ConfidenceClass",
    "DataProvenance",
    "EquilibriumPair",
    "GasTransportPair",
    "LiquidTransportPair",
    "PackingSpec",
    "SoluteSpec",
    "SolventSpec",
    "REFERENCE_ID",
    "ReferenceDataBundle",
    "locked_reference_data",
    "AbsorberDataRegistry",
    "RegistryError",
    "DuplicateRegistrationError",
    "UnknownEntityError",
    "MissingPairDataError",
    "PairAvailability",
    "RegistryReadiness",
    "build_reference_registry",
    "PropertyResolver",
    "PropertyResolutionError",
    "MissingPropertyError",
    "UnsupportedPropertyModelError",
    "InvalidPropertyOverrideError",
    "ResolutionTier",
    "ResolvedProperty",
    "CorrelationEstimate",
    "ComponentPropertyOverrides",
    "CarrierPropertyOverrides",
    "SolventPropertyOverrides",
    "ResolvedCarrierState",
    "ResolvedSolventState",
    "ResolvedEquilibrium",
    "ResolvedComponentProperties",
    "build_reference_resolver",
]

# Phase 11 — built-in transport-property estimation correlations
from .estimation_validation import (
    ESTIMATION_SOLUTE_ID,
    ESTIMATION_CARRIER_ID,
    ESTIMATION_SOLVENT_ID,
    PHASE11_ESTIMATION_CASE_ID,
    Phase11EstimationReport,
    build_phase11_estimation_registry,
    run_phase11_estimation_gate,
)

__all__.extend([
    "CorrelationCalculation",
    "CorrelationInputError",
    "fuller_gas_diffusivity_m2_s",
    "wilke_chang_liquid_diffusivity_m2_s",
    "ESTIMATION_SOLUTE_ID",
    "ESTIMATION_CARRIER_ID",
    "ESTIMATION_SOLVENT_ID",
    "PHASE11_ESTIMATION_CASE_ID",
    "Phase11EstimationReport",
    "build_phase11_estimation_registry",
    "run_phase11_estimation_gate",
])


# Phase 10 — synthetic generic chemistry verification
from .synthetic_validation import (
    SYNTHETIC_CASE_ID,
    SYNTHETIC_CARRIER_ID,
    SYNTHETIC_PACKING_ID,
    SYNTHETIC_SOLUTES,
    SYNTHETIC_SOLVENT_ID,
    SyntheticGenericReport,
    audit_core_for_legacy_identifiers,
    build_synthetic_registry,
    run_synthetic_generic_case,
    synthetic_boundaries,
    synthetic_operating_point,
)

__all__.extend([
    "SYNTHETIC_CASE_ID",
    "SYNTHETIC_CARRIER_ID",
    "SYNTHETIC_PACKING_ID",
    "SYNTHETIC_SOLUTES",
    "SYNTHETIC_SOLVENT_ID",
    "SyntheticGenericReport",
    "audit_core_for_legacy_identifiers",
    "build_synthetic_registry",
    "run_synthetic_generic_case",
    "synthetic_boundaries",
    "synthetic_operating_point",
])
